#!/bin/bash

export SRC_CONTAINER_IMAGE_REGISTRY_URL=sagcr.azurecr.io
export SRC_CONTAINER_IMAGE_REGISTRY_USER=''
export SRC_CONTAINER_IMAGE_REGISTRY_PASS=''

export DST_CONTAINER_IMAGE_REGISTRY_URL=gccdevopsacr.azurecr.io
export DST_CONTAINER_IMAGE_REGISTRY_USER=''
export DST_CONTAINER_IMAGE_REGISTRY_PASS=''